server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${HOST_PG}:${PORT_PG}/${NAME_DB}
    username: ${USER_PG}
    password: ${PASS_PG}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA}
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug